# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b413e0801910c9a32d151beded4393aa8c34b4e231702d25f34b74f2ea124bc84fd9611a5a4a49dc2b0d0b236dd31bf6cc966a2debb5242127e3c9d36491d06

test:
  secret_key_base: f8e1e3e1f58bdb354ed0eb16f5f21060c7fca0341f87375c7b22b8a6e53f7de256676a195e9703c19edf2bcedc0c5cc7a20c38b3f9f1f3c0e93dc1eb3ab61fca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
